FROM alpine:3
WORKDIR /workspace

ARG TARGETARCH
ARG TARGETOS
ARG TERRAFORM_VERSION='1.12.2'
ARG TFLINT_VERSION='0.58.1'
ARG TRIVY_VERSION='0.65.0'

# Install tools used to install other packages
RUN : \
    && apk update \
    && apk add --no-cache \
        curl \
        zip

# Install basic dependencies.
RUN : \
    && apk update \
    && apk add --no-cache \
        bash \
        git

# Install pre-commit.
RUN : \
    && apk update \
    && apk add --no-cache \
        pre-commit

# Install Terraform.
RUN : \
    && curl "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_${TARGETOS}_${TARGETARCH}.zip" \
        --fail-with-body \
        --location \
        --output /tmp/terraform.zip \
        --show-error \
        --silent \
    && unzip -d /tmp/terraform -q /tmp/terraform.zip \
    && rm -f /tmp/terraform.zip \
    && mv /tmp/terraform/terraform /usr/local/bin/terraform \
    && rm -rf /tmp/terraform

# Install tflint.
RUN : \
    && curl "https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_${TARGETOS}_${TARGETARCH}.zip" \
        --fail-with-body \
        --location \
        --output /tmp/tflint.zip \
        --show-error \
        --silent \
    && unzip -d /tmp/tflint -q /tmp/tflint.zip \
    && rm -f /tmp/tflint.zip \
    && mv /tmp/tflint/tflint /usr/local/bin/tflint \
    && rm -rf /tmp/tflint

# Install Trivy.
COPY ./lib/trivy/install.sh .
RUN : \
    && ./install.sh "${TRIVY_VERSION}" \
    && rm install.sh

# Remove tools used to install other packages
RUN apk del \
    curl \
    unzip
