FROM alpine:3
WORKDIR /workspace

ARG TARGETARCH
ARG TARGETOS
ARG TERRAFORM_VERSION='1.12.2'
ARG TERRAGRUNT_VERSION='0.84.0'

# Install tools used to install other packages
RUN : \
    && apk update \
    && apk add --no-cache \
        curl \
        zip

# Install basic dependencies.
RUN : \
    && apk update \
    && apk add --no-cache \
        bash \
        git

# Install pre-commit.
RUN : \
    && apk update \
    && apk add --no-cache \
        pre-commit

# Install Terraform.
RUN : \
    && curl "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_${TARGETOS}_${TARGETARCH}.zip" \
        --fail-with-body \
        --location \
        --output /tmp/terraform.zip \
        --show-error \
        --silent \
    && unzip -d /tmp/terraform -q /tmp/terraform.zip \
    && rm -f /tmp/terraform.zip \
    && mv /tmp/terraform/terraform /usr/local/bin/terraform \
    && rm -rf /tmp/terraform

# Install Terragrunt.
RUN : \
    && curl "https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_${TARGETOS}_${TARGETARCH}" \
        --fail-with-body \
        --location \
        --output /usr/local/bin/terragrunt \
        --show-error \
        --silent

# Remove tools used to install other packages
RUN apk del \
    curl \
    unzip
