jobs:
  build-and-push:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - id: timestamp
        name: Generate timestamp
        run: echo "timestamp=$(date +%Y-%m-%dT%H-%M-%SZ)" >>"${GITHUB_OUTPUT}"
      - id: ghcr-login
        name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./infrastructure/Containerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.timestamp.outputs.timestamp }}
name: push to main
on:
  push:
    branches:
      - main
