jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./infrastructure/Containerfile
          platforms: linux/amd64,linux/arm64
          push: false
name: pr to main
on:
  pull_request:
    branches:
      - main
