jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./infrastructure/Containerfile
          push: false
name: pr to main
on:
  pull_request:
    branches:
      - main
